In [1]:
import re
import math
from hazm import *
import numpy as np
import pandas as pd
from string import punctuation
from collections import Counter
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2

In [2]:
normalizer = Normalizer()
lemmatizer = Lemmatizer()

In [3]:
def load_datatset():
    dataset = pd.read_csv('dataset/ProjectData.csv')
    dataset = dataset[['comment','label']]
    dataset = dataset[dataset['label'] != -2]
    dataset = dataset.dropna()
    return dataset

In [4]:
def undersampl_data(dataset):
    counts = dataset['label'].value_counts()
    min_count = counts.min()
    undersampled_df = pd.concat([dataset[dataset['label'] == Label].sample(n=min_count)
                                 for Label in counts.index])
    return undersampled_df

In [5]:
dataset = load_datatset()
dataset['label'] += 2

In [6]:
dataset = undersampl_data(dataset)
dataset

comment  label
57113  بنظرم که کفش خوبیهمن که پوشیدمش واقعا احساس را...    3.0
1503           این کتاب فوق العادست به همه پیشنهاد میکنم    3.0
42098  توپ بسیار خوب و زیبایی است که کنترل آن راحت و ...    3.0
52830  کیفیتش خیلی عالیهفوق العاده شیک و خوش دستحتما ...    3.0
39279  خیلی عالیه . واقعا کیفیتشو بعد خرید میبینید . ...    3.0
...                                                  ...    ...
53028       بیشتر بدرد مغازه و جای تقریبا ثابت میخوره...    2.0
57     من اول می خواستم این هدفون رو از دیجی کالا بگی...    2.0
12811                                        معمولیه کلا    2.0
9263   خوبه باحاله فقط رنگش متفاوته باعکس و اینکه قسم...    2.0
42245  به نظر من که هدست خوبی هست ولی خیلی ظریفه و نم...    2.0

[16881 rows x 2 columns]

In [7]:
counts = dataset['label'].value_counts()
counts

3.0    5627
1.0    5627
2.0    5627
Name: label, dtype: int64

In [8]:
def tokenize_text(text):
    text = normalizer.normalize(text)
    text = text.replace('.', ' ')
    text = re.sub('\s+', ' ', text).strip()
    text = text.replace('\u200c', ' ').replace('\n', '').replace('\r', '').replace('ي', 'ی').replace('ك', 'ک')
    tokens = word_tokenize(text)
    return tokens

In [9]:
def create_word_set(comments):
    word_set = set()
    for comment in comments:
        for token in comment:
            word_set.add(token)
    return word_set

In [10]:
def preprocessing(comment):
    stop_words = ['و', 'در', 'به', 'از', 'که', 'این', 'را', 'با', 'است', 'برای', 'آن', 'یک', 'خود', 'تا', 'کرد', 'بر', 'هم', 'نیز', 'گفت', 'می\u200cشود', 'وی', 'شد', 'دارد', 'ما', 'اما', 'یا', 'شده', 'باید', 'هر', 'آنها', 'بود', 'او', 'دیگر', 'دو', 'مورد', 'می\u200cکند', 'شود', 'کند', 'وجود', 'بین', 'پیش', 'شده_است', 'پس', 'نظر', 'اگر', 'همه', 'یکی', 'حال', 'هستند', 'من', 'کنند', 'نیست', 'باشد', 'چه', 'بی', 'می', 'بخش', 'می\u200cکنند', 'همین', 'افزود', 'هایی', 'دارند', 'راه', 'همچنین', 'روی', 'داد', 'سه', 'داشت', 'چند', 'سوی', 'تنها', 'هیچ', 'میان', 'اینکه', 'شدن', 'بعد', 'جدید', 'ولی', 'حتی', 'کردن', 'برخی', 'کردند', 'می\u200cدهد', 'اول', 'نه', 'کرده_است', 'نسبت', 'بیش', 'شما', 'چنین', 'طور', 'افراد', 'تمام', 'درباره', 'بار', 'بسیاری', 'می\u200cتواند', 'کرده', 'چون', 'ندارد', 'دوم', 'بزرگ', 'طی', 'حدود', 'همان', 'بدون', 'البته', 'آنان', 'می\u200cگوید', 'دیگری', 'خواهد_شد', 'کنیم', 'قابل', 'یعنی', 'رشد', 'می\u200cتوان', 'وارد', 'کل', 'ویژه', 'قبل', 'براساس', 'نیاز', 'گذاری', 'هنوز', 'لازم', 'سازی', 'بوده_است', 'چرا', 'می\u200cشوند', 'وقتی', 'گرفت', 'کم', 'جای', 'حالی', 'تغییر', 'پیدا', 'اکنون', 'تحت', 'باعث', 'مدت', 'فقط', 'تعداد', 'آیا', 'بیان', 'رو', 'شدند', 'عدم', 'کرده_اند', 'بودن', 'نوع', 'بلکه', 'جاری', 'دهد', 'برابر', 'مهم', 'بوده', 'اخیر', 'مربوط', 'امر', 'زیر', 'گیری', 'شاید', 'خصوص', 'آقای', 'اثر', 'کننده', 'بودند', 'فکر', 'کنار', 'اولین', 'سوم', 'سایر', 'کنید', 'ضمن', 'مانند', 'باز', 'می\u200cگیرد', 'ممکن', 'حل', 'دارای', 'پی', 'مثل', 'می\u200cرسد', 'اجرا', 'دور', 'منظور', 'کسی', 'موجب', 'طول', 'امکان', 'آنچه', 'تعیین', 'گفته', 'شوند', 'جمع', 'علاوه', 'گونه', 'تاکنون', 'رسید', 'ساله', 'گرفته', 'شده_اند', 'علت', 'چهار', 'داشته_باشد', 'خواهد_بود', 'طرف', 'تهیه', 'تبدیل', 'مناسب', 'زیرا', 'مشخص', 'می\u200cتوانند', 'نزدیک', 'جریان', 'روند', 'بنابراین', 'می\u200cدهند', 'یافت', 'نخستین', 'بالا', 'پنج', 'ریزی', 'چیزی', 'نخست', 'بیشتری', 'ترتیب', 'شده_بود', 'خاص', 'شروع', 'فرد', 'کامل', 'غیر', 'می\u200cرود', 'دهند', 'آخرین', 'دادن', 'جدی', 'بهترین', 'شامل', 'گیرد', 'بخشی', 'باشند', 'تمامی', 'بهتر', 'داده_است', 'حد', 'نبود', 'کسانی', 'می\u200cکرد', 'داریم', 'علیه', 'می\u200cباشد', 'دانست', 'ناشی', 'داشتند', 'دهه', 'می\u200cشد', 'ایشان', 'آنجا', 'گرفته_است', 'دچار', 'می\u200cآید', 'لحاظ', 'آنکه', 'داده', 'بعضی', 'هستیم', 'اند', 'برداری', 'نباید', 'می\u200cکنیم', 'نشست', 'سهم', 'همیشه', 'آمد', 'اش', 'وگو', 'می\u200cکنم', 'حداقل', 'طبق', 'جا', 'خواهد_کرد', 'نوعی', 'چگونه', 'رفت', 'هنگام', 'فوق', 'روش', 'ندارند', 'سعی', 'بندی', 'شمار', 'کلی', 'کافی', 'مواجه', 'همچنان', 'سمت', 'کوچک', 'داشته_است', 'چیز', 'پشت', 'آورد', 'حالا', 'روبه', 'سال\u200cهای', 'دادند', 'می\u200cکردند', 'عهده', 'نیمه', 'جایی', 'دیگران', 'سی', 'بروز', 'یکدیگر', 'آمده_است', 'جز', 'کنم', 'سپس', 'کنندگان', 'خودش', 'همواره', 'یافته', 'شان', 'صرف', 'نمی\u200cشود', 'رسیدن', 'چهارم', 'یابد', 'متر', 'ساز', 'داشته', 'کرده_بود', 'باره', 'نحوه', 'کردم', 'تو', 'شخصی', 'داشته_باشند', 'محسوب', 'پخش', 'کمی', 'متفاوت', 'سراسر', 'کاملا', 'داشتن', 'نظیر', 'آمده', 'گروهی', 'فردی', 'ع', 'همچون', 'خطر', 'خویش', 'کدام', 'دسته', 'سبب', 'عین', 'آوری', 'متاسفانه', 'بیرون', 'دار', 'ابتدا', 'شش', 'افرادی', 'می\u200cگویند', 'سالهای', 'درون', 'نیستند', 'یافته_است', 'پر', 'خاطرنشان', 'گاه', 'جمعی', 'اغلب', 'دوباره', 'می\u200cیابد', 'لذا', 'زاده', 'گردد', 'اینجا']
    REPLACE_NO_SPACE = re.compile("[.`;:!\'?,\"()\[\]،؛ًٌٍَُِّ]")
    REPLACE_NUMBER_ENGLISH = re.compile("[0-9A_Za-z۰-۹]")
    comment = [REPLACE_NO_SPACE.sub("", line) for line in comment]
    comment = [REPLACE_NUMBER_ENGLISH.sub("", line) for line in comment]
    comment = ''.join(c for c in comment if not c.isdigit())
    comment = ''.join(c for c in comment if c not in punctuation)
    comment = normalizer.normalize(comment)
    tokens = word_tokenize(comment)
    cleared_text = []
    for word in tokens:
        word = normalizer.normalize(word)
        word = lemmatizer.lemmatize(word)
        if word not in stop_words and len(word) > 1:
            cleared_text.append(word)
    return cleared_text

In [11]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
tokens = []
for i in range(len(X)):
    tokens.append(preprocessing((X[i])))

In [13]:
def DF(tokens):
    word_counts = Counter(word for feature in tokens for word in set(feature))
    total_comments = len(tokens)
    upper_threshold = total_comments * 0.8
    lower_threshold = total_comments * 0.001
    pruned_tokens_features = []
    for feature in tokens:
        pruned_feature = [word for word in feature if word_counts[word] < upper_threshold and word_counts[word] >= lower_threshold]
        pruned_tokens_features.append(pruned_feature)
    return pruned_tokens_features

In [14]:
tokens = DF(tokens)

In [15]:
def TF_IDF(tokens):
    tf = []
    for doc in tokens:
        doc_tf = {}
        for word in doc:
            doc_tf[word] = doc.count(word) / len(doc)
        tf.append(doc_tf)
    idf = {}
    for doc in tokens:
        for word in set(doc):
            if word in idf:
                idf[word] += 1
            else:
                idf[word] = 1
    num_docs = len(tokens)
    for word in idf:
        idf[word] = math.log((1 + num_docs) / (1 + idf[word])) + 1
    tfidf = []
    for doc in tf:
        doc_tfidf = {}
        for word in doc:
            doc_tfidf[word] = doc[word] * idf[word]
        tfidf.append(doc_tfidf)
    
    # Normalize the TF-IDF score for each word in each document
    for i in range(len(tfidf)):
        tfidf_values = list(tfidf[i].values())
        norm = math.sqrt(sum(x**2 for x in tfidf_values))
        for word in tfidf[i]:
            tfidf[i][word] /= norm  
    vocab = sorted(set(word for doc in tokens for word in doc))
    matrix = [[doc.get(word, 0) for word in vocab] for doc in tfidf]
    matrix = np.array(matrix)
    return matrix

In [16]:
matrix = TF_IDF(tokens)
matrix.shape

(16881, 1920)

In [17]:
X_new = SelectKBest(chi2, k=300).fit_transform(matrix, y)

In [18]:
# Logistic Regression Functions
def sigmoid(z):
    h = 1 / (1 + np.exp(-z))
    return h

def logistic_prediction(X, theta, threshold=0.5, norm=False):
    z = np.dot(X, theta.T)
    h = sigmoid(z)
    if not norm:
        return h
    else:
        if threshold == 0.5:
            yh = np.array([1 if label >= threshold else 0 for label in h]).reshape(-1, 1)
        else:
            yh = np.array([1 if label >= threshold else 0 for label in h]).reshape(-1, 1)
        return yh

def logistic_gradient(X, y, alpha, n_iter):
    m_sample, n_feature = X.shape
    theta = np.random.rand(n_feature).reshape(-1, n_feature)
    iter_cost = []
    for i in range(n_iter):
        pred = logistic_prediction(X, theta)
        change = []
        for j in range(n_feature):
            change.append((np.dot(X[:, j], (pred - y))) / m_sample)
            theta[0][j] = theta[0][j] - alpha * change[j]
        cost = abs(sum(change))
        iter_cost.append(cost)
    return theta[0], np.array(iter_cost)

def calc_cross_entropy(X, y, theta):
    m_sample = X.shape[0]
    ones = np.ones(m_sample)
    h = logistic_prediction(X, theta)
    ce = -(np.dot(y.T, np.log(h)) + np.dot((ones - y).T, np.log(ones - h))) / m_sample
    return ce[0]

In [19]:
# Our Logistic Regression

# Preparing Data
X_1v2 = X_new[np.where(y != 3)]
X_1v3 = X_new[np.where(y != 2)]
X_2v3 = X_new[np.where(y != 1)]

y_1v2 = y[y != 3]
y_1v3 = y[y != 2]
y_2v3 = y[y != 1]

y_1v2 = np.array([0 if y == 1 else 1 for y in y_1v2]).reshape(-1, 1)
y_1v3 = np.array([0 if y == 1 else 1 for y in y_1v3]).reshape(-1, 1)
y_2v3 = np.array([0 if y == 2 else 1 for y in y_2v3]).reshape(-1, 1)

X_train_1v2, X_test_1v2, y_train_1v2, y_test_1v2 = train_test_split(X_1v2, y_1v2, test_size=0.2, random_state=42)
X_train_1v3, X_test_1v3, y_train_1v3, y_test_1v3 = train_test_split(X_1v3, y_1v3, test_size=0.2, random_state=42)
X_train_2v3, X_test_2v3, y_train_2v3, y_test_2v3 = train_test_split(X_2v3, y_2v3, test_size=0.2, random_state=42)

# Train Phase Of 1 VS 2
theta_1v2, cost_1v2 = logistic_gradient(X_train_1v2, y_train_1v2, 0.1, 10000)

# Test Phase Of 1 VS 2
yh_train_1v2 = logistic_prediction(X_train_1v2, theta_1v2, norm=True)
yh_test_1v2 = logistic_prediction(X_test_1v2, theta_1v2, norm=True)

train_ce_1v2 = calc_cross_entropy(X_train_1v2, y_train_1v2, theta_1v2)
test_ce_1v2 = calc_cross_entropy(X_test_1v2, y_test_1v2, theta_1v2)

train_acc_1v2 = accuracy_score(y_train_1v2, yh_train_1v2)
test_acc_1v2 = accuracy_score(y_test_1v2, yh_test_1v2)

# Results For 1 VS 2
print('1 VS 2:')
print(f'Train Cross Entropy: {train_ce_1v2.round(2)} | Test Cross Entropy: {test_ce_1v2.round(2)}')
print(f'Train Accuracy: {round(train_acc_1v2 * 100, 2)} | Test Accuracy: {round(test_acc_1v2 * 100, 2)}\n')

# Train Phase Of 1 VS 3
theta_1v3, cost_1v3 = logistic_gradient(X_train_1v3, y_train_1v3, 0.1, 10000)

# Test Phase Of 1 VS 3
yh_train_1v3 = logistic_prediction(X_train_1v3, theta_1v3, norm=True)
yh_test_1v3 = logistic_prediction(X_test_1v3, theta_1v3, norm=True)

train_ce_1v3 = calc_cross_entropy(X_train_1v3, y_train_1v3, theta_1v3)
test_ce_1v3 = calc_cross_entropy(X_test_1v3, y_test_1v3, theta_1v3)

train_acc_1v3 = accuracy_score(y_train_1v3, yh_train_1v3)
test_acc_1v3 = accuracy_score(y_test_1v3, yh_test_1v3)

# Results For 1 VS 3
print('1 VS 3:')
print(f'Train Cross Entropy: {train_ce_1v3.round(2)} | Test Cross Entropy: {test_ce_1v3.round(2)}')
print(f'Train Accuracy: {round(train_acc_1v3 * 100, 2)} | Test Accuracy: {round(test_acc_1v3 * 100, 2)}\n')

# Train Phase Of 2 VS 3
theta_2v3, cost_2v3 = logistic_gradient(X_train_2v3, y_train_2v3, 0.1, 10000)

# Test Phase Of 2 VS 3
yh_train_2v3 = logistic_prediction(X_train_2v3, theta_2v3, norm=True)
yh_test_2v3 = logistic_prediction(X_test_2v3, theta_2v3, norm=True)

train_ce_2v3 = calc_cross_entropy(X_train_2v3, y_train_2v3, theta_2v3)
test_ce_2v3 = calc_cross_entropy(X_test_2v3, y_test_2v3, theta_2v3)

train_acc_2v3 = accuracy_score(y_train_2v3, yh_train_2v3)
test_acc_2v3 = accuracy_score(y_test_2v3, yh_test_2v3)

# Results For 2 VS 3
print('2 VS 3:')
print(f'Train Cross Entropy: {train_ce_2v3.round(2)} | Test Cross Entropy: {test_ce_2v3.round(2)}')
print(f'Train Accuracy: {round(train_acc_2v3 * 100, 2)} | Test Accuracy: {round(test_acc_2v3 * 100, 2)}\n')

1 VS 2:
Train Cross Entropy: 0.57 | Test Cross Entropy: 0.58
Train Accuracy: 71.68 | Test Accuracy: 71.04

1 VS 3:
Train Cross Entropy: 0.45 | Test Cross Entropy: 0.45
Train Accuracy: 81.64 | Test Accuracy: 81.61

2 VS 3:
Train Cross Entropy: 0.57 | Test Cross Entropy: 0.57
Train Accuracy: 70.69 | Test Accuracy: 71.17



In [20]:
# Train Confusion Matrix
print(f'1V2 Train Confusion Matrix:\n {confusion_matrix(y_train_1v2, yh_train_1v2)}\n')
print(f'1V3 Train Confusion Matrix:\n {confusion_matrix(y_train_1v3, yh_train_1v3)}\n')
print(f'2V3 Train Confusion Matrix:\n {confusion_matrix(y_train_2v3, yh_train_2v3)}\n')

# Test Confusion Matrix
print(f'1V2 Test Confusion Matrix:\n {confusion_matrix(y_test_1v2, yh_test_1v2)}\n')
print(f'1V3 Test Confusion Matrix:\n {confusion_matrix(y_test_1v3, yh_test_1v3)}\n')
print(f'2V3 Test Confusion Matrix:\n {confusion_matrix(y_test_2v3, yh_test_2v3)}\n')

1V2 Train Confusion Matrix:
 [[2952 1542]
 [1008 3501]]

1V3 Train Confusion Matrix:
 [[3430 1079]
 [ 574 3920]]

2V3 Train Confusion Matrix:
 [[2747 1762]
 [ 877 3617]]

1V2 Test Confusion Matrix:
 [[752 381]
 [271 847]]

1V3 Test Confusion Matrix:
 [[ 830  288]
 [ 126 1007]]

2V3 Test Confusion Matrix:
 [[683 435]
 [214 919]]



In [21]:
# Softmax Functions
def one_hot_encode(y):
    m_sample = len(y)
    classes = np.unique(y)
    c_class = len(classes)
    one_hot = np.zeros((m_sample, c_class), int)
    for i in range(m_sample):
        for j, c in enumerate(classes):
            if y[i] == c:
                one_hot[i][j] = 1
    return one_hot

def softmax_prediction(X, theta, norm=False):
    z = np.dot(X, theta)
    h = np.exp(z - np.max(z, axis=1, keepdims=True))
    yh = h / np.sum(h, axis=1, keepdims=True)
    if not norm:
        return yh
    else:
        return np.argmax(yh, axis=1, keepdims=True) + 1

def softmax_gradient(X, y, alpha, n_iter):
    m_sample, n_feature = X.shape
    c_class = len(np.unique(y))
    theta = np.random.rand(n_feature, c_class)
    one_hot = one_hot_encode(np.array(y))
    iter_cost = []
    for i in range(n_iter):
        pred = softmax_prediction(X, theta)
        change = np.dot(X.T, (pred - one_hot))
        theta = theta - alpha * np.array(change)
        cost = 0
        for c in range(c_class):
            cost += np.sum(one_hot[:, c] * np.log10(pred[:, c]))
        cost = -cost / m_sample
        iter_cost.append(cost)
    return theta, iter_cost[-1].round(2)

In [22]:
# Our Softmax
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

class_theta, cross_entropy = softmax_gradient(X_train, y_train, 0.01, 100)

yh_train = softmax_prediction(X_train, class_theta, True)
yh_test = softmax_prediction(X_test, class_theta, True)

acc_train = accuracy_score(np.array(y_train).reshape(-1, 1), yh_train)
acc_test = accuracy_score(np.array(y_test).reshape(-1, 1), yh_test)

print('Softmax Regression Result:')
print(f'Cross Entropy: {cross_entropy}')
print(f'Train Accuracy: {round(acc_train * 100, 2)} | Test Accuracy: {round(acc_test * 100, 2)}\n')

Softmax Regression Result:
Cross Entropy: 0.32
Train Accuracy: 67.17 | Test Accuracy: 66.8



In [23]:
print(f'Train Confusion Matrix:\n {confusion_matrix(y_train, yh_train)}\n')
print(f'Test Confusion Matrix:\n {confusion_matrix(y_test, yh_test)}\n')

Train Confusion Matrix:
 [[3260  813  379]
 [1075 2514  959]
 [ 450  757 3297]]

Test Confusion Matrix:
 [[858 222  95]
 [258 573 248]
 [102 196 825]]



In [24]:
# Scikit-Learn Logistic Regression
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=250)
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f'Train Accuracy Using Library: {round(train_accuracy * 100, 2)}')
print(f'Test Accuracy Using Library: {round(test_accuracy * 100, 2)}')
print()
print(f'Train Confusion Matrix:\n{confusion_matrix(y_train, y_train_pred)}\n')
print(f'Test Confusion Matrix:\n{confusion_matrix(y_test, y_test_pred)}\n')

Train Accuracy Using Library: 67.76
Test Accuracy Using Library: 67.25

Train Confusion Matrix:
[[3090 1080  282]
 [ 849 2920  779]
 [ 362 1002 3140]]

Test Confusion Matrix:
[[815 293  67]
 [206 675 198]
 [ 99 243 781]]



In [25]:
# Naive Bayes Functions
def class_probability(label):
    m_sample = len(label)
    _, count = np.unique(label, return_counts=True)
    class_prob = count / m_sample
    return class_prob

def index_probability(data, label):
    unique, count = np.unique(label, return_counts=True)
    c_class = len(unique)
    m_sample = len(label)
    n_feature = 28 * 28
    index_prob = np.zeros((n_feature, c_class, 2))
    for m in range(m_sample):
        for i in range(300):
            if data[m][i] == 0:
                index_prob[i][label[m]][0] += 1
            elif data[m][i] != 0:
                index_prob[i][label[m]][1] += 1
    for n in range(n_feature):
        for c in range(c_class):
            for v in range(2):
                index_prob[n][c][v] = index_prob[n][c][v] / count[c]
    return index_prob

def naive_bayes_prediction(data, c_prob, i_prob):
    c_class = len(c_prob)
    m_sample = len(data)
    data_pred = np.zeros((m_sample, 1), int)
    for i, d in enumerate(data):
        pred_arr = c_prob.copy()
        for j in range(300):
            for m in range(c_class):
                if d[j] == 0:
                    pred_arr[m] *= i_prob[j][m][0]
                elif d[j] != 0:
                    pred_arr[m] *= i_prob[j][m][1]
        data_pred[i][0] = np.argmax(pred_arr)
    return data_pred

In [26]:
# Our Naive Bayes
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)
y_train = np.array(y_train.astype(int) - 1)
y_test = np.array(y_test.astype(int) - 1)

class_prob = class_probability(y_train)
index_prob = index_probability(X_train.tolist(), y_train)

data_pred_train = naive_bayes_prediction(X_train, class_prob, index_prob)
data_pred_test = naive_bayes_prediction(X_test, class_prob, index_prob)

naive_bayes_acc_train = accuracy_score(y_train.reshape(-1, 1), data_pred_train.reshape(-1, 1))
naive_bayes_acc_test = accuracy_score(y_test.reshape(-1, 1), data_pred_test.reshape(-1, 1))

print('Train Accuracy: ' + str(round(naive_bayes_acc_train * 100, 2)))
print('Test Accuracy: ' + str(round(naive_bayes_acc_test * 100, 2)))

Train Accuracy: 65.54
Test Accuracy: 66.48


In [27]:
print(f'Train Confusion Matrix:\n {confusion_matrix(y_train, data_pred_train)}\n')
print(f'Test Confusion Matrix:\n {confusion_matrix(y_test, data_pred_test)}\n')

Train Confusion Matrix:
 [[3270  780  402]
 [1168 2328 1052]
 [ 505  746 3253]]

Test Confusion Matrix:
 [[873 207  95]
 [279 546 254]
 [105 192 826]]



In [28]:
# Scikit-Learn Naive Bayes
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

clf = MultinomialNB()
clf.fit(X_train, y_train)

train_accuracy = clf.score(X_train, y_train)
test_accuracy = clf.score(X_test, y_test)

print(f'Train Accuracy {round(train_accuracy * 100, 2)}')
print(f'Test Accuracy {round(test_accuracy * 100, 2)}')
print()
print(f'Train Confusion Matrix:\n {confusion_matrix(y_train, clf.predict(X_train))}\n')
print(f'Test Confusion Matrix:\n {confusion_matrix(y_test, clf.predict(X_test))}\n')

Train Accuracy 66.69
Test Accuracy 66.12

Train Confusion Matrix:
 [[2917 1115  420]
 [ 752 2884  912]
 [ 300  999 3205]]

Test Confusion Matrix:
 [[772 304  99]
 [195 656 228]
 [ 79 239 805]]



In [29]:
# Our SVM
def svm (X,Y,C):
    learning_rate = 0.01
    _samples,_features = X.shape
    w = np.zeros((1, _features))
    b = 0
    for i in range(600):
        gradw = 0
        gradb = 0
        for idx, x_i in enumerate(X):
            if Y[idx] * (np.dot(w, x_i.T) + b)> 1:
                gradw += 0
                gradb += 0
            else:
                gradw += C * Y[idx] * x_i
                gradb += C * Y[idx]  
        w = w - learning_rate * w + learning_rate * gradw
        b = b + learning_rate * gradb
    return w,b

def predict(X,w,b):
    prediction = np.dot(X, w[0]) + b 
    return np.sign(prediction)

In [30]:
# Our SVM
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

#Preparing Data
X_1v2 = X_train[np.where(y_train != 3)]
X_1v3 = X_train[np.where(y_train != 2)]
X_2v3 = X_train[np.where(y_train != 1)]

y_1v2 = y_train[y_train != 3]
y_1v3 = y_train[y_train != 2]
y_2v3 = y_train[y_train != 1]

y_1v2 = np.array([-1 if y == 1 else 1 for y in y_1v2]).reshape(-1, 1)
y_1v3 = np.array([-1 if y == 1 else 1 for y in y_1v3]).reshape(-1, 1)
y_2v3 = np.array([-1 if y == 2 else 1 for y in y_2v3]).reshape(-1, 1)

w1V2, b1v2 = svm(X_1v2, y_1v2, 100)
w1V3, b1v3 = svm(X_1v3, y_1v3, 100)
w2V3, b2v3 = svm(X_2v3, y_2v3, 100)

y_pre1v2 = predict(X_test, w1V2, b1v2)
y_pre1v3 = predict(X_test, w1V3, b1v3)
y_pre2v3 = predict(X_test, w2V3, b2v3)

y_pre1v2 = [1 if y == -1 else 2 for y in y_pre1v2]
y_pre1v3 = [1 if y == -1 else 3 for y in y_pre1v3]
y_pre2v3 = [2 if y == -1 else 3 for y in y_pre2v3]

# Maximum Majority 
y_pre = []
for y in range(len(y_pre1v2)):
    temp = []
    temp.append(y_pre1v2[y])
    temp.append(y_pre1v3[y])
    temp.append(y_pre2v3[y])
    label_1 = temp.count(1)
    label_2 = temp.count(2)
    label_3 = temp.count(3)
    if label_1 == max(label_1, label_2, label_3):
        y_pre.append(1)
        continue
    if label_2 == max(label_1, label_2, label_3):
        y_pre.append(2) 
        continue
    if label_3 == max(label_1, label_2, label_3):
        y_pre.append(3) 
        continue
        
accuracy = accuracy_score(y_test, y_pre) 

print("Accuracy: ", round(accuracy * 100, 2))

Accuracy:  39.41


In [31]:
print(confusion_matrix(y_test, y_pre))

[[1173    2    0]
 [1064    4   11]
 [ 967    2  154]]


In [32]:
from sklearn import svm
clf = svm.SVC(kernel='linear', decision_function_shape='ovr')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", round(accuracy * 100, 2))
print(confusion_matrix(y_test, y_pred))

Accuracy:  66.92
[[781 337  57]
 [163 738 178]
 [ 84 298 741]]
